<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-02-05T16:34:37 IST" name="Suite" finished-at="2022-02-05T16:34:40 IST" duration-ms="3138">
    <groups>
    </groups>
    <test started-at="2022-02-05T16:34:37 IST" name="Test" finished-at="2022-02-05T16:34:40 IST" duration-ms="3138">
      <class name="com.scrolltest.api.tests.DataDrivenExamples">
        <test-method signature="test_delete2(int)[pri:0, instance:com.scrolltest.api.tests.DataDrivenExamples@2b72cb8a]" started-at="2022-02-05T16:34:37 IST" name="test_delete2" finished-at="2022-02-05T16:34:40 IST" duration-ms="2831" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_delete2 -->
        <test-method signature="test_post(java.lang.String, java.lang.String, int)[pri:0, instance:com.scrolltest.api.tests.DataDrivenExamples@2b72cb8a]" started-at="2022-02-05T16:34:40 IST" name="test_post" data-provider="DataForPost" finished-at="2022-02-05T16:34:40 IST" duration-ms="0" status="FAIL">
          <exception class="org.testng.TestNGException">
            <message>
              <![CDATA[
Found two providers called 'DataForPost' on class com.scrolltest.api.tests.DataDrivenExamples]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestNGException: 
Found two providers called 'DataForPost' on class com.scrolltest.api.tests.DataDrivenExamples
at org.testng.internal.Parameters.findDataProvider(Parameters.java:661)
at org.testng.internal.Parameters.findDataProvider(Parameters.java:551)
at org.testng.internal.Parameters.handleParameters(Parameters.java:772)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:789)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestNGException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_post -->
      </class> <!-- com.scrolltest.api.tests.DataDrivenExamples -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
